### ISSUE TITLE
Current Directory and the Directory of the image are different

### ISSUE THREAD

**Issue by oshezaf** [OTRF/OSSEM-CDM#10]
https://github.com/OTRF/OSSEM-CDM/blob/dacbc880b04e9b8ca0ae07b42614c1e0f9bcc8bf/schemas/entities/process.yml#L35

The current process entity includes the field 'process_file_directory" which is documented to be the current directory, and the image path. Those are not the same. I suggest adding a field called process_current_directory.

**Comment by Cyb3rPandaH** [comment]
Hey @oshezaf @Cyb3rWard0g, hope you guys are doing well. Here some ideas about this issue 😃 

The current definition of the field **file_directory** makes reference to the folder or place or container where the image file related to the process is being stored. It also specifies that it represents the **current** directory.

That being said, if we move the time or progress context **current** to the field name, which makes sense, are we considering also other fields such as **previous** or **old** to complement the schema? I would add both data fields if we have telemetry that provides them (Current and previous). Otherwise, I would continue using the name **file_directory** making reference to the current directory.

**Comment by Cyb3rWard0g** [comment]
Event Sample:

![image](https://user-images.githubusercontent.com/9653181/130707211-1806d839-686e-4f1a-9527-163143464bb8.png)

Hello @oshezaf , a few things we are considering for this. We agree with you:
* `file_path` and `file_directory` -> They are only related to the `File` entity and not the process
* `process_current_directory` -> It is related to the `Process` entity.

A few things we are doing:
* We are updating the description for `file_directory` to be the `file_path` without the name of the file
* We are adding the new attribute `process_current_directory` and adding the following description from MS docs API:

```
The full path to the current directory for the process. The string can also specify a UNC path.
```

Reference: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa
